//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlyphViewer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlyphViewer.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glyph Viewer.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BackButtonLabel {
            get {
                return ResourceManager.GetString("BackButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenSansRegular.
        /// </summary>
        internal static string DefaultFontFamily {
            get {
                return ResourceManager.GetString("DefaultFontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The width to use to display the currently selected glyph..
        /// </summary>
        internal static string GlyphWidthDescription {
            get {
                return ResourceManager.GetString("GlyphWidthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glyph Width.
        /// </summary>
        internal static string GlyphWidthLabel {
            get {
                return ResourceManager.GetString("GlyphWidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font size to use to display the glyphs in the currently selected font..
        /// </summary>
        internal static string ItemFontSizeDescription {
            get {
                return ResourceManager.GetString("ItemFontSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Font Size.
        /// </summary>
        internal static string ItemFontSizeLabel {
            get {
                return ResourceManager.GetString("ItemFontSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font size to use to display the name of  Glyphs group.
        /// </summary>
        internal static string ItemHeaderFontSizeDescription {
            get {
                return ResourceManager.GetString("ItemHeaderFontSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Header Font Size.
        /// </summary>
        internal static string ItemHeaderFontSizeLabel {
            get {
                return ResourceManager.GetString("ItemHeaderFontSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of the font to use to display the title..
        /// </summary>
        internal static string TitleFontSizeDescription {
            get {
                return ResourceManager.GetString("TitleFontSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Font Size.
        /// </summary>
        internal static string TitleFontSizeLabel {
            get {
                return ResourceManager.GetString("TitleFontSizeLabel", resourceCulture);
            }
        }
    }
}
