//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlyphViewer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlyphViewer.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glyph Viewer.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BackButtonLabel {
            get {
                return ResourceManager.GetString("BackButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark the current font family.
        /// </summary>
        internal static string BookmarkCommandDescription {
            get {
                return ResourceManager.GetString("BookmarkCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        internal static string BookmarkGroupName {
            get {
                return ResourceManager.GetString("BookmarkGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tallest glyph in the font..
        /// </summary>
        internal static string CellHeightDefaultDescription {
            get {
                return ResourceManager.GetString("CellHeightDefaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tallest glyph in the row..
        /// </summary>
        internal static string CellHeightDynamicDescription {
            get {
                return ResourceManager.GetString("CellHeightDynamicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines how glyphs are arranged in the Glyphs View..
        /// </summary>
        internal static string CellLayoutDescription {
            get {
                return ResourceManager.GetString("CellLayoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CellLayout.
        /// </summary>
        internal static string CellLayoutStyleName {
            get {
                return ResourceManager.GetString("CellLayoutStyleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The widest glyph in the font..
        /// </summary>
        internal static string CellWidthDefaultDescription {
            get {
                return ResourceManager.GetString("CellWidthDefaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The width of the glyph..
        /// </summary>
        internal static string CellWidthDynamicDescription {
            get {
                return ResourceManager.GetString("CellWidthDynamicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The widest glyph in the row..
        /// </summary>
        internal static string CellWidthRowDescription {
            get {
                return ResourceManager.GetString("CellWidthRowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied..
        /// </summary>
        internal static string CopiedText {
            get {
                return ResourceManager.GetString("CopiedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy all glyphs in the font to the clipboard.
        /// </summary>
        internal static string CopyFontDescription {
            get {
                return ResourceManager.GetString("CopyFontDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Glyph metrics to the clipboard.
        /// </summary>
        internal static string CopyGlyphMetricsDescription {
            get {
                return ResourceManager.GetString("CopyGlyphMetricsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenSansRegular.
        /// </summary>
        internal static string DefaultFontFamily {
            get {
                return ResourceManager.GetString("DefaultFontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the font..
        /// </summary>
        internal static string FamilyNameDescription {
            get {
                return ResourceManager.GetString("FamilyNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string FamilyNameLabel {
            get {
                return ResourceManager.GetString("FamilyNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font attributes to use for the font..
        /// </summary>
        internal static string FontAttributesDescription {
            get {
                return ResourceManager.GetString("FontAttributesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Attributes.
        /// </summary>
        internal static string FontAttributesLabel {
            get {
                return ResourceManager.GetString("FontAttributesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Attributes.
        /// </summary>
        internal static string FontAttributesName {
            get {
                return ResourceManager.GetString("FontAttributesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of the font in points.
        /// </summary>
        internal static string FontSizeDescription {
            get {
                return ResourceManager.GetString("FontSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        internal static string FontSizeLabel {
            get {
                return ResourceManager.GetString("FontSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glyphs.
        /// </summary>
        internal static string GlyphCountName {
            get {
                return ResourceManager.GetString("GlyphCountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Height.
        /// </summary>
        internal static string GlyphItemHeightLabel {
            get {
                return ResourceManager.GetString("GlyphItemHeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Width.
        /// </summary>
        internal static string GlyphItemWidthLabel {
            get {
                return ResourceManager.GetString("GlyphItemWidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glyph Preview.
        /// </summary>
        internal static string GlyphPreviewLayout {
            get {
                return ResourceManager.GetString("GlyphPreviewLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings defined for a glyph..
        /// </summary>
        internal static string GlyphSettingDescription {
            get {
                return ResourceManager.GetString("GlyphSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glyph Preview.
        /// </summary>
        internal static string GlyphSettingLabel {
            get {
                return ResourceManager.GetString("GlyphSettingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The width to use to display the currently selected glyph..
        /// </summary>
        internal static string GlyphWidthDescription {
            get {
                return ResourceManager.GetString("GlyphWidthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glyph Width.
        /// </summary>
        internal static string GlyphWidthLabel {
            get {
                return ResourceManager.GetString("GlyphWidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font to use to display the glyphs in the currently selected font..
        /// </summary>
        internal static string ItemFontDescription {
            get {
                return ResourceManager.GetString("ItemFontDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Font Size.
        /// </summary>
        internal static string ItemFontName {
            get {
                return ResourceManager.GetString("ItemFontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font to use to display the name of  Glyphs group.
        /// </summary>
        internal static string ItemHeaderFontDescription {
            get {
                return ResourceManager.GetString("ItemHeaderFontDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Header Font.
        /// </summary>
        internal static string ItemHeaderFontLabel {
            get {
                return ResourceManager.GetString("ItemHeaderFontLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string OpenSettingsDescription {
            get {
                return ResourceManager.GetString("OpenSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset settings to the default values..
        /// </summary>
        internal static string ResetSettingsDescription {
            get {
                return ResourceManager.GetString("ResetSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for glyphs by text in the name or the code..
        /// </summary>
        internal static string SearchEntryDescription {
            get {
                return ResourceManager.GetString("SearchEntryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter search text.
        /// </summary>
        internal static string SearchEntryPlaceholdText {
            get {
                return ResourceManager.GetString("SearchEntryPlaceholdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of the font to use to display the title..
        /// </summary>
        internal static string TitleFontDescription {
            get {
                return ResourceManager.GetString("TitleFontDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Font Size.
        /// </summary>
        internal static string TitleFontLabel {
            get {
                return ResourceManager.GetString("TitleFontLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings for the GlyphViewer.
        /// </summary>
        internal static string UserSettingsDescription {
            get {
                return ResourceManager.GetString("UserSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string UserSettingsLabel {
            get {
                return ResourceManager.GetString("UserSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write all glyphs in the font to a file.
        /// </summary>
        internal static string WriteFontDescription {
            get {
                return ResourceManager.GetString("WriteFontDescription", resourceCulture);
            }
        }
    }
}
